TRI-AMDD/beep

beep/structure.py

Adds split diagnostic cycling (authored by @chirranjeevigopal-TRI).
I've also done a few cleanup-oriented things in this PR, namely:
* Minor formatting on beep.structure.py
* Moved the default diagnostic_available setting outside of the conditional so as to cover all cases (previously diagnostic_available could be unset with a unspecified diagnostic criteria in the parameter file).
* Removed the `v_range` and `resolution` parameters from RawCyclerRun.to_processed_cycler_run, since they weren't being used.

MAT-1359 - add split step indices to public repo

---

beep/__init__.py
beep/tests/test_collate.py
beep/tests/test_end_to_end.py
beep/tests/test_events.py
beep/tests/test_features.py
beep/tests/test_models.py
beep/tests/test_principal_components.py
beep/tests/test_protocol.py
beep/tests/test_splice.py
beep/tests/test_structure.py
beep/tests/test_validate.py
beep/utils/events.py
beep/utils/splice.py

This PR is isolating all of the python logic for the tests into the tests, which consists of:
* Declaring TEST_DIR and TEST_FILES_DIR in each test
* Removing TEST_DIR and TEST_FILES_DIR in beep.__init__.py
* Creates a dedicated LOG_DIR to replace the use of TEST_FILE_DIR in beep.events and beep.splice
Also:
* Few housekeeping things (upper-case module-level constants)

Standalone tests

---

beep/generate_protocol.py

Method to add waveform step (based on drive-cycle) into the procedure file.
This can be invoked from one of the procedure generation functions once we have an appropriate template to get the right step number from.

add waveform step

---

beep/config.py
beep/tests/test_events.py
beep/utils/events.py
beep/utils/secrets_manager.py

This PR changes the configuration of the kinesis stream so that it pulls from secrets manager instead of being hardcoded.
WARNING: This is a breaking change for ECS so should not be merged into master until we have switched to Kubernetes

Switch over the kinesis event stream name 

---

beep/generate_protocol.py
beep/procedure_templates/PreDiag_parameters - DP.csv
beep/procedure_templates/diagnosticV4.000
beep/tests/test_files/data-share/raw/parameters/PreDiag_parameters - GP.csv
beep/tests/test_protocol.py

This PR makes updates necessary to create the procedure files for Batch 3
- Add a template diagnosticV4.000 which has a lower voltage safety cutoff of 2.0V instead of 2.5V
- Wrap the staggered rest times so that the rest time does not get longer than 6.2 hours
- Allow the second charge current to be larger than the first.

Mat 1490 updates for batch3

---

beep/structure.py
beep/tests/test_structure.py

PR to 
- add cumulative charge capacity and charge energy as columns to the summary dataframe
- exclude diagnostic cycles from regular summary calc.

add cumulative capacity to summary stats

---

beep/structure.py
beep/tests/test_structure.py

This PR addresses the assertion error and changes it to a soft error that gets logged. The purpose is to allow processing to proceed even if there is no parameter data for that particular file.

Mat 1542 change assertion to error log

---

beep/structure.py
beep/tests/test_structure.py

This PR doubles the resolution of the diagnostic interpolation to address issues in fitting the response of the battery to pulses. This could potentially also create problems in the pipeline due to memory issues.

Increase the resolution of diagnostic interpolation from 500 to 1000

---

beep/structure.py

Memory use is decreased, according to memory-profiler. Would appreciate confirmation that these new commands are equivalent to the previous version. Also added some .loc calls to get rid of pandas warning related to "Returning a view vs a copy" (https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#indexing-view-versus-copy).
[mem_profile_before.txt](https://github.com/TRI-AMDD/beep/files/4453146/mem_profile_before.txt)
[mem_profile_after.txt](https://github.com/TRI-AMDD/beep/files/4453148/mem_profile_after.txt)

MAT-1603 Reduce memory and reduce warnings

---

beep/structure.py
beep/tests/test_structure.py

This PR changes the paused column to be an int value instead of a boolean. Following convention, 0 is False and 1 is True. This change is necessary to prevent errors in the data syncer and the UI

Change the paused column in the summary data to be int type

---

beep/generate_protocol.py

This PR capitalizes the protocol generator event service name so that events are appropriately handled by consuming services.

MAT-1637: Capitalize Protocol Generator Service Name

---

beep/utils/events.py

This PR adds a new line to all Kinesis put_record calls to allow for later splitting and parsing of events stored via Firehose.

MAT-1641: Add Newline To put_record Data

---

beep/config.py
beep/conversion_schemas/__init__.py
beep/conversion_schemas/structured_dtypes.yaml
beep/structure.py
beep/tests/test_structure.py

This PR adds type casting for the structured data in an attempt to reduce memory required for subsequent processing.
- Schema for data types in each of the structured dataframes
- `astype` calls to cast each dataframe to those data types upon creation
- tests to ensure that data is typed correctly
- logic around reloading dataframes and casting the data types
Memory usage of `diagnostic_interpolated` and `cycles_interpolated` before and after data typing

Cast data types for all data frames in the structure

---

beep/__init__.py
beep/config.py
beep/featurize.py
beep/run_model.py
beep/structure.py
beep/validate.py

This PR changes the way that logging to stdout is done in a stage environment to more closely mirror BEEP-Sync (which is cleaner and easier). It also adds some retry logic around setting up the logger so that credential errors don't immediately cause the container to crash.

Change logging to stdout to cleaner method

---

beep/__init__.py
beep/utils/events.py

This PR adds retry logic around getting the secret for the event stream. I am not sure why this is necessary since the credentials must be available for initializing the logger to get to this point, but it's possible that the method for getting credentials is slightly different for secrets.

Add retry logic to events

---

beep/featurize.py
beep/structure.py
beep/tests/test_secrets_manager.py
beep/tests/test_structure.py
beep/utils/project_transfer.py
beep/utils/secrets_manager.py

This PR fixes some errors with the interpolation for regular cycles. Memory usage might be increased as a result, although this interpolation was already being done so the effect should be minimal. The processed object is significantly larger on disk (29MB -> 47MB). However, this change is necessary to complete some research on degradation features.
- Removes code that was deleting the charge step from regular cycles
- Changes charge interpolation to be based on capacity instead of voltage

Fix charge step interpolation for regular cycles

---

beep/structure.py
beep/tests/test_structure.py

This PR changes the interpolation axis for regular cycles to be computed as the maximum range in the run instead of just interpolating over the range for each cycle. This is necessary in order to subtract of two capacity-voltage curves from different cycles within the same run, a quantity related to the delta Q feature.

Change the interpolation axis to be the max range across the run

---

beep/featurize.py
beep/helpers/featurizer_helpers.py
beep/tests/test_features.py
setup.py

Initial PR for adding diagnostic cycles based features in the new featurization framework.
- All relevant helper functions for generating the feature object are dumped in /helpers/featurizer_helpers.py. We can discuss grouping them into classes of helpers, in support of the respective featurizer. 
- I did quite a bit of clean-up of the code, but considerable refactor of code is still necessary for consistency in variable names, docstrings and assertions need to be added.

Mat 1647 add diagnostic cycles feature classes

---

README.md
beep/__init__.py
beep/collate.py
beep/featurize.py
beep/generate_protocol.py
beep/run_model.py
beep/structure.py
beep/tests/test_collate.py
beep/tests/test_end_to_end.py
beep/tests/test_events.py
beep/tests/test_features.py
beep/tests/test_models.py
beep/tests/test_protocol.py
beep/tests/test_structure.py
beep/tests/test_validate.py

This is a new version of the Issue #45 PR that has been rebased to include new feature tests. This PR changes exception handling for the test setup and makes creation of directories automatic.
-Testing occurs in a variety of different environments and it's not possible to anticipate all of the exceptions that might occur when AWS resources are not available (no internet connection, no AWS credentials, incorrect credentials). Since the correct response to all of these situations is the same (proceed without AWS resources), having a general exception for this case seems justified.
-For new users, having to setup/understand the directory structure for the files is an unnecessary complication. As long as BEEP_PROCESSING_DIR is set correctly, creating the necessary directories for the files …

Issue 45 change directory creation

---

beep/conversion_schemas/arbin_conversion.yaml
beep/structure.py
beep/tests/test_structure.py

This PR adds data types to the Arbin raw data as an initial attempt to reduce the memory footprint.
- Added section to the arbin schema for data types
- Data types are applied immediately after loading the data into a dataframe

Add data types to arbin

---

beep/featurize.py
beep/helpers/featurizer_helpers.py
beep/tests/test_features.py

PR adds a new class for storing outcomes for to predict trajectory of degradation. 
- Validation criteria are inherited from the class DiagnosticCyclesFeatures
- Outcome is calculated as fractional amount of a quantity (most commonly discharge energy or capacity) remaining relative to the first cycle at every diagnostic cycle, for each diagnostic cycle type (e.g. 'hppc', 'reset' ). If there are 5 unique diagnostic_cycles, 2 degradation quantities of interest and 10 eligible sets of  diagnostic cycles, there will be 100 rows in X
- Currently, the threshold above which the outcomes are calculated is hard-coded. These will be made into class arguments in a follow-up PR.
Features and outcomes derived from diagnostic cycles are now part of the pipeline

Add outcomes as features

---

beep/tests/test_end_to_end.py
beep/tests/test_features.py
beep/tests/test_models.py
beep/tests/test_protocol.py
beep/tests/test_secrets_manager.py
beep/tests/test_structure.py
beep/tests/test_validate.py
beep/utils/secrets_manager.py

PR to fix an [issue](https://github.com/TRI-AMDD/beep/issues/54) relating to AWS credentialing. 
In the test class setup, I check if `secret_accessible(ENVIRONMENT)` returns True. If not, mode is set to `events_off`.  This should handle situations where a user has an AWS account, but not the right secrets for beep aws resources.

WIP: Mat 1735 turn off events if secrets not accessible

---

beep/config.py
beep/tests/test_events.py

This PR attempts to address Issue #54 by skipping event testing when the correct AWS resources are not available.

Alter connection try to avoid tests when correct AWS not present

---

setup.py

Should fix unittest issue, installs pytest-cov without pytest dependency conflict.

try pytest-cov removal

---

beep/tutorials/quick-start.ipynb

This PR adds a jupyter notebook with an example of how to install beep, download some example data from the fastcharge dataset, and run the full data pipeline.

Include notebook used to demonstrate the use of beep 

---

beep/config.py

This PR changes the logging configuration for 'local' to avoid test errors

Change logging options in the config for local to eliminate some errors

---

beep/tests/test_validate.py
beep/validate.py
beep/validation_schemas/schema-arbin-nmc-phev.yaml
beep/validation_schemas/schema-projects.yaml

This PR adds some structure around validation so that different projects can use different validation schemas.
- yaml file with project names and corresponding validation schemas
- new validation schema for Iris data
- test to make sure that the FastCharge project gets the right validation schema

Mat 1776 validation for new arbin projects

---

beep/validation_schemas/schema-arbin-nmc-phev.yaml

This PR opens the temperature range for xIris and Iris validation since some of the temperature channels seem to be malfunctioning and cannot be repaired due to limited lab access.

Open full temperature range for validation

---

beep/features/featurizer_helpers.py

Updated one of the helper functions for class HPPCRelaxationFeatures to handle errors caused due to occasional size mismatches between expected vs actual number of calculated SOC windows
In the fig attached, there should be only one relaxation curve around t=120000 and max 10 SOC windows.

MAT-1962 featurization failure

---

README.md

This PR updates the Readme test badge to use the one supplied by GitHub Actions.

MAT-1930: Update Test Badge

---

tasks.py

This PR adds a newline to the end of the file when the release process is invoked so that the linting check passes.

Add newline to end of init and setup

---

beep/protocol/biologic_mb_to_maccor.py
beep/tests/test_biologic_mb_to_maccor.py
beep/tests/test_files/biologic_mb_test_strs.py

Here be dragons. 
This PR implements the structural transformations of a Biologic Modulo Bat protocol to an equivalent protocol in Maccor's Procedure format.
There are two main methods:
`convert` which intakes a file and writes a file
`biologic_mb_text_to_maccor_xml` which takes in the already loaded text from a file and returns the equivalent xml for Maccor.
There are a number of structural constraints that are imposed on all incoming files:
- Nested loops are forbidden, the way Maccor and Biologic implement nested loops is fundamentally incompatible as far as I can tell. From my reading a nested loop in Biologic will only loop over the inner loop during the _first_ loop of the outer loop. On subsequent iterations of the outer loop, the inner loop will run once. This is not representable …

MAT-1973 Biologic mb to Maccor converter (part 2)

---

beep/structure.py
beep/tests/test_structure.py

This PR changes the content of the paused metric in the summary to be the length of the gap between data points in seconds.

Make changes so that paused is the number of seconds 

---

beep/features/featurizer_helpers.py
beep/tests/test_features.py

This PR resolves a problem with the `get_v_diff` function used in featurization. For some files the change in the interpolation axis from point to point to smaller than the floating point precision used in `interp1d` This results in the interpolation failing due to a non-strict monotonic trend in the axis `ValueError: Expect x to be a 1-D sorted array_like.`
- Added a test file where this problem occurs.
- Changed the method to remove redundant points when they exist
- Added a test with a file that does cause the error and file that does not to ensure that values are not changed due to the alteration in the method.

Create test and test file to resolve error

---

.coveragerc
.github/workflows/beep-lint.yml
.github/workflows/beep-test-pr.yml
.github/workflows/beep-test.yml
setup.cfg

This PR sets up pytest to ignore test files in the coverage report.
Note: Coverage has decreased and it appears that [`/beep/utils/secrets_manager.py:55`](https://coveralls.io/builds/34090576/source?filename=beep%2Futils%2Fsecrets_manager.py#L55) may be the cause. It looks like this line is covered in tests on the master branch, but not in PR branches.

MAT-2042: Setup Coverage Config

---

beep/structure.py

Fix #122 
Previously:
- Arbin metadata file was only nominally required for using RawCyclerRun
Now:
- Arbin metadata is not required, empty metadata is provided if no _Metadata is found
- a warning is thrown via logging to warn user the metadata file is not present

Fix arbin metadata requirement

---

beep/structure.py
beep/tests/test_structure.py

Quick PR splits `determine_whether_step_is_waveform` into separate method for waveform discharge and waveform charge.

add filters for waveform discharge and charge

---

beep/dataset.py
beep/features/featurizer_helpers.py
beep/structure.py
beep/tests/test_features.py
beep/tests/test_structure.py
beep/utils/__init__.py
beep/utils/parameters_lookup.py

This PR fixes a bug so that the summary attribute no longer includes the diagnostic cycles. It also changes the throughput calculation to separate throughput due to regular and diagnostic cycles.
- Adds the argument to pass the diagnostic_available to the `get_summary` function
- Adds assert statements to a test to ensure that summary no longer contains the diagnostic cycles
- Changes the throughput calculation
- Removes initialization cycle from the throughput calculation
- Adds diagnostic interval information

Fix structuring and throughput feature

---

beep/tests/test_structure.py

This PR adds an assert to check that `test_time` is in the regular interpolated cycles

Add assert to ensure columns for regular interpolated cycles

---

beep/features/featurizer_helpers.py
beep/tests/test_features.py

This PR adds parsing for runs where the protocol field has a normed path instead of just a file name. It also imputes `0` for `NaN` values in the throughput since these are occurring where there are no cycles to accumulate
- Add parsing to the protocol name extraction
- Impute `0` for throughput with `NaN` values

Add parsing and NaN handling for `get_fractional_quantity_remaining_nx`

---

beep/generate_protocol.py
beep/tests/test_protocol.py

Updates `generate_protocol` to handle partial success better.
Now if, say, 28 of 30 possible files are generated we will report:
- The number completed out of the total possible
- The number failed out of the total possible
- A list of the protocol files successfully generated
- A list of the failures to generate a protocol file

MAT-2014 Handles partial success poorly

---

beep/generate_protocol.py

Creates parent directory if it does not exist rather than throwing error.

MAT-2013 error if parent directory does not exist

---

beep/dataset.py
beep/features/featurizer_helpers.py
beep/featurize.py
beep/tests/test_dataset.py

- PR to add `seq_num` as one of the fields in `BeepDataset.data`.
- When multiple feature-sets are merged, JOIN is performed on both `file` and `seq_num`. This allows runs with potentially same `seq_num` from different projects to be assembled in the same dataset.
- Also handles MAT-2141: exposes `parameters_path` in methods occurring in featurizer_helpers, featurize and dataset modules

add seq_num to dataset.data attribute, and expose parameters_path in datasets and features

---

beep/dataset.py
beep/features/featurizer_helpers.py
beep/tests/test_dataset.py

PR to add 
- tests for serialization/deserialization of BeepDataset class
- tests for dataset generation from processed_cycler_run objects with custom hyperparam sets. For instance, RPTdQdVFeatures can be generated for the different rpt cycles in the same dataset.

serialization and custom hyperparam tests for datasets

---

beep/generate_protocol.py
beep/protocol/procedure_templates/diagnosticV5.000
beep/tests/test_protocol.py

This PR adds a template for the PreDiag project. The template avoids a problem with the earlier version where exiting a step due to a safety condition in the final diagnostic could lead to an infinite loop.

Change the exit step for safety to avoid an infinite loop 

---

beep/conversion_schemas/structured_dtypes.yaml
beep/structure.py

Change the datatype for `paused` summary attribute to be `int32`.  Since `paused` evaluates max pause duration in seconds, `int8` type was leading to negative values anytime 127 was exceeded.

Fix negative paused values

---

beep/validation_schemas/schema-arbin-18650-2170.yaml
beep/validation_schemas/schema-arbin-nmc-phev.yaml
beep/validation_schemas/schema-maccor-2170.yaml

This PR changes the voltage limits for validation to allow processing of files where the cell has been disconnected at the end of the test so the voltage floats.
- Change upper limit to 5V
- Change lower limit to 0V
Tested with "xIris_000002_0000B2_CH3.csv" and "PreDiag_000298_000159.008" to make sure structuring succeeds and these files are now marked as valid.

Change the validation voltage limits

---

beep/features/featurizer_helpers.py
beep/tests/test_dataset.py
beep/tests/test_features.py

This PR adds additional statistics to `get_hppc_ocv()` as well as standardizes the `get_v_diff()` keys.
Tests have been added to check the output, but need to be checked by a researcher.

MAT-2304: Add Additional Statistics To get_hppc_ocv

---

beep/conversion_schemas/structured_dtypes.yaml
beep/structure.py
beep/tests/test_features.py
beep/tests/test_structure.py

This PR addresses problems around the charge and discharge energy in the structured data.
- Adds charge and discharge energy to the regular interpolated cycles
- Removes values from the regular summary resulting from errors in the raw data

Mat 2195 add energy to interpolated cycles and fix bad data

---

beep/featurize.py
beep/tests/test_features.py

This PR updates the DeltaQFastCharge feature class to use standard pandas indexing selection instead of lists. Output of the feature class is unchanged in tests.
- Passes index lists to `.iloc` which has the required behavior
- Add condition for creating the feature class to ensure basic indexing columns are present

Change pandas indexing usage to use iloc instead of straight lists

---

beep/protocol/arbin.py
beep/protocol/biologic.py
beep/tests/test_protocol.py
beep/utils/__init__.py

Updates `DashOrderedDict.get` (which previously overrided the OrderedDict.get method) - to `get_path`, which doesn't interfere with the new pydash api.

refactor DashOrderedDict.get to DashOrderedDict.get_path

---

beep/__init__.py

This PR makes the `BEEP_ENV` and `BEEP_PROCESSING_DIR` environment variables optional by defaulting to `local` for `BEEP_ENV` and the current working directory for `BEEP_PROCESSING_DIR`.
Fixes #116

MAT-2489: Make Environment Variables Optional

---

beep/protocol/biologic_templates/BioTest_000001.000.technique_1_cycle_rules.json
beep/protocol/biologic_templates/BioTest_000001.000.technique_2_cycle_rules.json
beep/protocol/biologic_templates/BioTest_000001.000.technique_4_cycle_rules.json
beep/protocol/maccor_to_biologic_mb.py
beep/tests/test_maccor_to_biologic_mb.py

This PR is a first attempt at calculating cycle number in output data based on the protocol used to generate it.
For @patrickherring-TRI 
The basic scheme (which handles a deceptively large number of edge cases)
- Preprocess the steps based on how you will split them into techniques, now each technique can only have loops one deep
- For each technique we create 
- a mapping of transitions between physical steps (e.g. constant current) that advance cycle and how much. **NOTE** We do not handle cycle advancement via GOTOs currently, but they are not important to our current protocols and can be added to this scheme later without any friction.
- the number of cycle advancement to perform when a technique loops
- the number of cycle advancements to perform when a technique ends
there is some …

Loop advances

---

beep/dataset.py
beep/features/featurizer_helpers.py
beep/tests/test_dataset.py
beep/tests/test_features.py

This PR adds a column "epoch_time" that is the timestamp in seconds of the cycle metric that is being calculated. This should make it possible to use epoch time in the threshold calculations

Add epoch time as a column in throughput calculations

---

beep/tests/test_features.py

This PR contains minor changes to test to make them compatible with the latest release of pandas which has a different accuracy for values.

Change tests to make them compatible with pandas 1.3.0

---

beep/conversion_schemas/arbin_conversion.yaml
beep/conversion_schemas/maccor_conversion.yaml
beep/conversion_schemas/neware_conversion.yaml
beep/conversion_schemas/structured_dtypes.yaml
beep/structure/base.py
beep/structure/battery_archive.py
beep/tests/test_structure_base.py
docs_src/writing_your_own.md

Adds cv_time and cv_current as summary stats to the regular cycles and diagnostic cycles. cv_time is the length of the CV segment of charge (useful for CV with current limit), and cv_current is the current at the end of the segment (useful for CV with time limit).
Also changes test_time from float32 to float64 in order to handle large times without decimal truncation.

CV summary stats

---

beep/structure/base.py
beep/tests/test_structure_base.py
beep/tests/test_structure_cyclerpaths.py
beep/utils/waveform.py

This PR changes the interpolation of the diagnostic cycles so that cv steps are interpolated on time instead of voltage. This is important so that enough points are included for feature extraction.

Working version of new interpolation

---

.github/workflows/beep-test.yml
beep/tests/test_features.py
requirements.txt

This PR updates the versions of boto to resolve some dependency issues. It also updates the featurization test from raw data. It appears that the switch of test_time and test (sec) from float32 to float64 changes the resistance values in the feature.

Change versions of boto and update tests

---

beep/features/intracell_analysis.py
beep/features/intracell_losses.py
beep/tests/test_intracell_analysis.py

* Adds a condition to `IntracellFeatures.validate_data` to test for empty eol diagnostic cycles.
* Adds an associated test
* Renames constants in `IntracellAnalysis` to be accessible at the class, rather than instance level of the object

add test and validation for non-overlapping intracell criteria

---

beep/features/intracell_analysis.py

Resolves a bug in IntracellAnalysis.py. NaN values were propagating into the error metric for the optimizer, which led to the optimizer triggering an error. Now, the NaN values are dropped to avoid this error.

Resolve bugs in IntracellAnalysis.py

---

beep/features/intracell_analysis.py
beep/tests/test_intracell_analysis.py

Change the threshold for conducting the intracell analysis from 0.8 to 0.7, so that we may be able to include at least one cycle that goes below 0.8. This way, we can interpolate the final states at 0.8 rather than extrapolate. Before this change, we would be guaranteed to not include the diagnostic with fractional metric below 0.8.

Extend intracell threshold

---

beep/structure/base.py

CV was occasionally not being extracted correctly for some cycles (see for example 'PreDiag_000447'). Part of the CC segment is sometimes included as CV. Decreasing the tolerance settings seems to fix the issue.

Decrease the tolerance for more accurate extraction of CV from CCCV

---

beep/protocol/maccor_to_biologic_mb.py

This fixes a bug for conversion of files where the goto in the maccor file points to the end step which has been removed. It is a combination of an off-by-one error and a typo in the variable name.

Fix error in converting formation files

---

beep/tests/test_files/goto_end_example.000
beep/tests/test_maccor_to_biologic_mb.py

This PR adds a test for[ this pull request ](https://github.com/TRI-AMDD/beep/pull/403) where the converter was crashing when the protocol contained a step that could GOTO the end step, and that step did not immediately precede the end step.
This PR includes a minimal example protocol: 2 physical steps, 1 end step, where the first step GOTOs the end step and a test that converts it.

test for goto end bug

---

beep/tests/test_cmd.py

Previously, stacktraces could not be captured in click+pytest for some reason, this just does not capture the stacktrace by preventing click CliRunner from internally catching exceptions

Fix CLI tests outputs

---

requirements.txt

Package would not install/run as-is due to matplotlib needing to be imported in some modules, and it not being listed under requirements.
Also, removed docopt as it is not needed.

Fix matplotlib requirement install issue

---

beep/cmd.py

This PR changes the separator for the suffix to underscore instead of hyphen to better match the previous file naming pattern.

Change suffix separator to better align with previous usage

---

beep/structure/base.py

Current structured_data saved in json.gz includes both raw data and structured data. 
Now:  reset default json file of structured data, so that structured_data is included, raw_data is not

Reset default saving option for structured_data: to not include raw_data 

---

beep/conversion_schemas/structured_dtypes.yaml
beep/structure/base.py
beep/structure/tests/test_base.py

This adds a CV capacity summary statistic for both regular and diagnostic cycles, which is distinct from the CV time and current stats I added previously. I included a regression test.
After merging I would appreciate a re-run of structuring on AWS for PreDiag and PredictionDiagnostics data sets.

CV capacity summary statistic

---

CHANGES.md
beep/__init__.py
setup.py

* Update beep contribution guideline
* Remove raw data from default structured files
* Adds a CV capacity summary stat.
* Drop testing for python 3.7 due to updating packages

v2022.5.2.14 release

---

README.md

- Was pulling `beep` for a project and was very surprised by quite how large the repo was. Thought that a badge in the readme showing the repo size would be helpful accordingly. Centered the badges to make them look nice.

Add repo-size badge and centre badges in readme

---

beep/structure/base.py
beep/structure/novonix.py
beep/structure/tests/test_cyclerpaths.py

- Previously, novonix ingestion failed silently (nans for all values of dchg cap and energy) on cycles where there are no charge steps, as the caps/engs could not be converted to montonically increasing since there was no max value from a charge step
- Now, explicitly accounts for these cycles with no charge step by setting the maximums from the highest raw `capacity` value within the cycle. Now the convention for these cycles is `discharge_capacity` = `max_discharge_capacity_within_this_cycle` - `capacity` (and similarly for energy). The other cycles are unchanged
- Also includes tests specifically for this case now in `test_cyclerpaths.TestNovonixDatapath.test_file_long` by looking explicitly at cycle 4.
- Also includes a warning when this extra conversion is needed. It looks like this: …

Bugfix novonix ingestion for cycles with no charge step
