beep/structure.py
beep/tests/test_structure.py

PR adds interpolation of date-time-iso field for diagnostic cycles.

interpolate date_time_iso for diagnostic cycles

---

beep/structure.py
beep/tests/test_structure.py

This PR changes the method for the interpolation of the HPPC cycle. Two problems exist in the current data; 1) the resolution of the voltage values is not high enough to allow for fitting of the kinetic parameters within a step 2) the data does not necessarily include the first and last voltage value for a step. This modification to the method attempts to address both of those problems while keeping the overall size of the data the same, by removing the rows that would normally have NaN values.
- Change the voltage interpolation for the hppc step to be on the voltage range in that iteration of the step.
- Set the resolution so that there is a default 0.5mV resolution for those steps
- Add cycle index as a column for the regular cycle summary (for reference development)

Change method for interpolation of the HPPC cycle

---

beep/structure.py

- Change a dataframe.apply to a series.where, which significantly decreases memory usage and compute time
- Slight vectorization of loop contents, with small decrease in compute time
Peak memory usage should really be decreased this time...

MAT-1603b - Reduce peak memory usage and compute time

---

README.md

Making a modification to the README file to explain environment variable setup.

Adding instructions to setup testing in README

---

beep/featurize.py
beep/tests/test_features.py

This PR adds a framework for feature generation. There is a base class that outlines the required methods and provides the workflow for feature generation. The derived classes implement methods for the actual creation of the feature object.
- Base feature class
- Derived class `DeltaQFeatures`
- Derived class `DeltaQFeaturesSingle`
[Feature generation classes.pdf](https://github.com/TRI-AMDD/beep/files/4603164/Feature.generation.classes.pdf)

Mat 1656 refactor featurization

---

beep/featurize.py
beep/run_model.py
beep/tests/test_end_to_end.py
beep/tests/test_features.py
beep/tests/test_models.py
beep/utils/project_transfer.py

This PR adds a framework for feature generation. There is a base class that outlines the required methods and provides the workflow for feature generation. The derived classes implement methods for the actual creation of the feature object.
- Base feature class
- Derived class `DeltaQFeatures`
- Derived class `DeltaQFeaturesSingle`
[Feature generation classes.pdf](https://github.com/TRI-AMDD/beep/files/4611199/Feature.generation.classes.pdf)

Refactor featurization into class objects

---

beep/featurize.py
beep/helpers/featurizer_helpers.py
beep/tests/test_features.py

- Left the helper functions as a module, as opposed to organizing into classes
- Added new features relating to relaxation time constants. 
- Also refactored some of the static methods into class methods for class DiagnosticCyclesFeatures

Mat 1717 reorganize helper funcs

---

beep/tests/test_models.py

Moved a couple of tests to scratch directory. Follow up PR for an [issue](https://github.com/TRI-AMDD/beep/issues/53)

run model tests in scratchDir

---

beep/featurize.py
beep/helpers/featurizer_helpers.py
beep/tests/test_features.py

I did not pass the 'nosetests', and the error message seems to be that the feature dataframe size is not equal to 90, maybe because I added many new feature? Now the hppc feature contains 54 resistances(different soc, charge/discharge, different time scale), a new feature-diffusion coeff for the short rest in hppc(the correlation for this is not very high), the variance of ocv, the variance of v_diff. I will continue to work on this, but I am so excited to submit my first pull request ever!

Modified hppc features

---

beep/validation_schemas/schema-projects.yaml

This PR adds the xIris project to supported schemas

Add xIris project to schemas

---

README.md

Add a small blurb to the README to let people know we are looking for a python developer for this package.

Looking for python dev

---

CONTRIBUTING.md
README.md

Adding a contributions.md file with guidelines for external contributions to the repo. Largely adapted and abbreviated from [PyBaMM](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md).

Mat 1806 guidelines for contributions

---

beep/featurize.py
beep/structure.py
beep/tests/test_events.py
beep/tests/test_features.py
beep/tests/test_structure.py
beep/tests/test_validate.py
beep/utils/__init__.py
beep/utils/events.py
beep/validate.py

This PR creates additional output files on the local file system to support processing via Argo workflows.

MAT-1870: Workflow Outputs

---

.github/workflows/beep-test.yml

This PR adds AWS credentials for retrieval of large files from S3 for testing purposes.

Adding AWS credentials for retrieval of S3 objects for testing

---

beep/features/featurizer_helpers.py
beep/featurize.py
beep/tests/test_features.py

This PR updates the `get_v_diff` method so that values are strictly monotonic with increase between values of `discharge_capacity` at least as big as the threshold.
- Threshold is computed as `(np.max(Q) - np.min(Q)) / 1e6`

Change the method for ensuring monotonicity and add testing 

---

beep/protocol/procedure_templates/Iris_parameters - GP.csv
beep/tests/test_tutorial.py
docs_src/tutorial.md

This PR just cleans up some of the artifacts from tests.

Remove extra parameter file

---

beep/utils/project_transfer.py

This PR updates the test bucket to `beep-sync-test-stage`.

MAT-2115: Change Test Bucket

---

beep/dataset.py

Adding index for comparing a specific element (a dict) of a list

add index for list of dicts key comparison

---

requirements.txt

This PR updates some of the requirements to more accurately reflect what is necessary for the package.

Update requirements for the package

---

beep/tests/test_validate.py
beep/validate.py
beep/validation_schemas/schema-maccor-2170.yaml

Add validation for `cycle_index` monotonicity.

Mat 2091 validation check monotonicity

---

beep/features/featurizer_helpers.py
beep/tests/test_features.py

This PR addresses an assertion error in the get_step_index function used featurization.
- Change the condition for the 'hppc_final_discharge' step

MAT-2267 Fix get_step_index

---

beep/tests/test_features.py

This PR adds a test to ensure that changes to the structuring module don't have downstream problems in featurization. Currently, the test files are static so changes won't necessarily be detected in the featurization module.

Adding test for raw file to features 

---

beep/features/featurizer_helpers.py
beep/tests/test_dataset.py
beep/tests/test_features.py

This PR adds additional statistics to get_v_diff.

MAT-2304: Add Additional Statistics To get_v_diff

---

beep/dataset.py
beep/features/featurizer_helpers.py
beep/tests/test_features.py

This PR adds support for rpt and reset cycles to the get_step_index function

Mat 2360 add rpt and reset to get step index

---

.github/dependabot.yml
.github/workflows/beep-test-pr.yml
.github/workflows/beep-test.yml
beep/tests/test_principal_components.py
requirements-docs.txt
requirements-test.txt
requirements.txt

Adds dependabot.yml and initial dependabot updates (from my fork).
Note that I accidentally merged these earlier, but reverted the changes.  Somehow the earlier dependency updates got lost in the reversion, so they're here.

MAT-2382 Dependabot

---

.github/workflows/beep-test.yml

Fix environment variable so that big tests run

Change environment variable for big tests

---

beep/features/featurizer_helpers.py
beep/featurize.py
beep/principal_components.py
beep/tests/test_features.py

This PR fixes several featurization failures occurring in an subset of the files
- get_step_index is modified to deal with situations where the hppc cycles soc windows are incomplete
- DeltaQFastCharge is modified to have better instantiation conditions
- New test file objects are created to match the new structuring code

Mat-2443 Fix featurization failures

---

beep/structure/base.py

Add necessary information for the logger in the base class. This addresses an error in the data pipeline.

Add service information into the base class for the logger

---

beep/protocol/maccor_to_biologic_mb.py
beep/tests/test_maccor_to_biologic_mb.py

This PR addresses changes necessary to get settings conversion to work on the BT-Lab system.
- Change abbreviations, range values and safety ranges
- Split any combined steps into separate seqs since only one control mode at a time is supported on BT-Lab system

Loop tech part2

---

beep/structure/__init__.py

Adding battery archive class to the structure imports

Add the battery archive class to the init

---

beep/dataset.py

This PR updates the threshold calculation per the suggestion by Patrick Asinger.

Update threshold method

---

beep/tests/test_files/PriorLAMVal_000101_000080_CH2_Metadata.csv
beep/tests/test_validate.py
beep/validation_schemas/schema-projects.yaml

This PR adds the ability to validate files for new projects LAMVal, and PriorLAMVal

Update validation for new projects

---

.github/workflows/beep-test-pr.yml
.github/workflows/beep-test.yml
beep/protocol/tests/test_protocol.py
beep/tests/test_cmd.py

Add windows testing back to for integration testing

Add back the windows testing for integration tests

---

beep/structure/novonix.py

allow from_file function to read raw novonix file

fix a bug to read novonix raw file

---

CHANGES.md
beep/__init__.py
setup.py

* Update NovonixDatapath with improved parsing capability (#687)

v2022.10.3.16 release
